# Generated by Django 4.2.23 on 2025-07-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('passout_year', models.CharField(max_length=15)),
                ('source', models.CharField(choices=[('instagram', 'instagram'), ('facebook', 'facebook'), ('referral', 'referral'), ('walkin', 'walkin')], default='walkin', max_length=100)),
                ('course', models.CharField(choices=[('TESTING', 'TESTING'), ('PYTHON DJANGO', 'PYTHON DJANGO'), ('MERN', 'MERN'), ('DATA SCIENCE', 'DATA SCIENCE'), ('JAVA SPRINGBOOT', 'JAVA SPRINGBOOT'), ('.NET', '.NET')], default='PYTHON DJANGO', max_length=100)),
                ('course_mode', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE'), ('HYBRID', 'HYBRID')], default='OFFLINE', max_length=20)),
                ('status', models.CharField(choices=[('FOLLOWUP', 'FOLLOW-UP'), ('PROCEEDTOADMISSION', 'PROCEED-TO-ADMISSION'), ('NOTINTERESTED', 'NOT-INTERESTED')], default='FOLLOWUP', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updadted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
